### ISSUE TITLE
🫴 proposal: change repo name

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/philippines-travel-level-map#17]
The current name `philippine-map-app` is too general compared to the actual usage of the app. My suggestion is to rename it to `philippines-travel-level-map` which describes the app's purpose really well.

**Comment by denzdelvillar** [comment]
Yup, agree with name change

**Comment by jofftiquez** [comment]
> Yup, agree with name change

Thanks for the confirmation @denzdelvillar. Do you want me to proceed with it or you're gonna do it yourself? Let me know thanks.

**Comment by warengonzaga** [comment]
> The current name `philippine-map-app` is too general compared to the actual usage of the app. My suggestion is to rename it to `philippines-travel-level-map` which describes the app's purpose really well.

Sounds good, more visibility too.

**Comment by denzdelvillar** [comment]
@jofftiquez I renamed na to `philippines-travel-level-map`
