### ISSUE TITLE
formatting and linting config

### ISSUE THREAD

**Issue by gballesteros10** [OSSPhilippines/philippines-travel-level-map#23]
since several devs are already contributing to this repo, formatting can be a challenge sometimes. without uniform formatting config, reviewing PRs can be inconvenient sometimes because there are affected lines without any change but formatting.

we can use Prettier and ESLint, or some other similar tools, to avoid those issues.

we can even take it a step further and use something like husky.

i'm not sure yet about the specs of the implementation, and how the rules would be agreed upon. so please feel free to add suggestions in this thread.

thanks.

cc: @warengonzaga

**Comment by gballesteros10** [comment]
also, a bit out of topic but if the plan is to maintain this project and make it bigger with new features, i think it's also good to consider using TypeScript.

we can create a separate issue for that if necessary.

**Comment by jofftiquez** [comment]
ESLint is good, also let's use semistandard

**Comment by warengonzaga** [comment]
We can utilize ROME for linting. Any thoughts?

**Comment by jofftiquez** [comment]
> We can utilize ROME for linting. Any thoughts?

Eslint for me

**Comment by warengonzaga** [comment]
Alright, if ESLint is easy to setup let's go for it.
