### ISSUE TITLE
Visual artefacts on mobile related to hover behavior

### ISSUE THREAD

**Issue by denzdelvillar** [OSSPhilippines/philippines-travel-level-map#24]
Hover behavior works well on desktop: Province name shows up and Province area becomes highlighted as gray. However on mobile, there is some visual artefact that seems to be related to the highlighting behavior for mouse hover. Refer to the video below:

https://user-images.githubusercontent.com/87693272/234027860-68a39288-53cd-4650-ab96-7bc222e58364.MOV

Clicking Albay at 00:06 produces a hover behavior to Northern Samar. Likewise, clicking Bukidnon at 00:11 produced the same behavior to Maguindanao del Sur.

**Comment by gballesteros10** [comment]
hi @denzdelvillar 

can't replicate this issue. tried on 2 mobiles phones, chrome and brave browser:
- Galaxy A71
- Galaxy A52S

what device are you testing it on?

**Comment by denzdelvillar** [comment]
> what device are you testing it on?

@gballesteros10 the video was recorded on Google Chrome ver `112.0.5615.70` on an iPhone 12 Pro Max with iOS `16.1.2`

Is there a way in React to know whether it is being rendered on a desktop browser or mobile browser? If yes, then i think the solution would be to disable the `:hover` css when it detects a mobile browser.

**Comment by jofftiquez** [comment]
> > what device are you testing it on?
> 
> @gballesteros10 the video was recorded on Google Chrome ver `112.0.5615.70` on an iPhone 12 Pro Max with iOS `16.1.2`
> 
> Is there a way in React to know whether it is being rendered on a desktop browser or mobile browser? If yes, then i think the solution would be to disable the `:hover` css when it detects a mobile browser.

This can be achieved by media query for css implementation. Otherwise, there's a native way to know the screen size using JS

**Comment by gballesteros10** [comment]
thanks for the info @denzdelvillar . nice, that solution could work.

and yes, there are ways in React and in JS to detect screen width. but same with @jofftiquez's comment, i think in this case css media query would be the more efficient approach.

will get back to this tomorrow after work.

**Comment by mackyclemen** [comment]
I would like to contribute to fix this bug - would it be alright if I do a PR?

**Comment by gballesteros10** [comment]
cool thanks. in that case, i will not be making any changes for now. let's wait for @mackyclemen's PR to be merged
