### ISSUE TITLE
✏️ Enhancement: Add a way to reset selected provinces

### ISSUE THREAD

**Issue by jofftiquez** [OSSPhilippines/philippines-travel-level-map#25]
After testing the map, and selected more than 10 provinces, I realized that there's no way to reset the map to the default state. 

https://www.my-philippines-travel-level.com/map?levels=00050000000350000000301000000000000000000005000300000000414005300000000000000000000

Maybe add a reset button

**Comment by chaaals** [comment]
hii @jofftiquez , I opened a PR for thiss :))
