### ISSUE TITLE
OG Image Tag on Twitter still not visible

### ISSUE THREAD

**Issue by fidellim** [OSSPhilippines/philippines-travel-level-map#29]
I have tested the main site using Localhost Open Graph Checker (chrome extension) and it works. 

Not sure why it still doesn't show on the live site. I am assuming it might be a hosting issue or it needs to be clear cached.

| Main Site | Localhost Open Graph Checker|
|--------|--------|
| ![image](https://user-images.githubusercontent.com/26820513/234770643-ed91a4c3-6160-42bf-90a0-f627f0c7172e.png)| ![image](https://user-images.githubusercontent.com/26820513/234770781-fb4737e7-bc7f-4ac5-aacd-4332c31db6f3.png)|

**Comment by fidellim** [comment]
I am not sure if Twitter has a debugger like Facebook. I have checked using Twitter Card Validator and this is the output:

<details><summary>Twitter Card Validator</summary>
<p>

https://cards-dev.twitter.com/validator

![image](https://user-images.githubusercontent.com/26820513/234813841-e034833c-a9ed-47c5-a217-e8c90b81d95b.png)


</p>
</details> 

I have tried it on this [link](https://tweetpik.com/twitter-card-validator) as well: 

<details><summary>Details</summary>
<p>

https://tweetpik.com/twitter-card-validator

![image](https://user-images.githubusercontent.com/26820513/234814114-a7d8b040-d89f-4065-a5c0-8729c28e2851.png)

</p>
</details>

**Comment by warengonzaga** [comment]
hey @fidellim I tried just now and pasted the link to the tweet but it display correctly.
![image](https://user-images.githubusercontent.com/15052701/234840525-b8493064-b6a6-49ff-b8c1-c872054dcd69.png)

**Comment by fidellim** [comment]
Hello @warengonzaga, it seems to be working on my side too! Did you do something to fix it?

<details><summary>Click to view</summary>
<p>

![image](https://user-images.githubusercontent.com/26820513/234843809-3f4fc051-ad3e-4903-aa07-c5cd83dee508.png)

</p>
</details>

**Comment by denzdelvillar** [comment]
I think we can close this issue. On my side it is also working perfectly.

**Comment by warengonzaga** [comment]
> Hello @warengonzaga, it seems to be working on my side too! Did you do something to fix it?
> 
> Click to view

It just needs to be refresh from twitter debugger
