### ISSUE TITLE
trunk based configuration for deployments

### ISSUE THREAD

**Issue by warengonzaga** [OSSPhilippines/philippines-travel-level-map#31]
Hey, @jofftiquez @denzdelvillar as following our latest workflow for trunk-based development adding this issue here as my reference for PR.

**Comment by jofftiquez** [comment]
Let me just drop this beautiful drawing of mine for future reference 🧑‍🎨🎨

![image](https://user-images.githubusercontent.com/8638243/234809354-3d9c4962-55d3-4e04-9ef7-ef7cfe0972b6.png)

**Comment by warengonzaga** [comment]
added #38
