### ISSUE TITLE
Facebook flags posts containing the link as spam

### ISSUE THREAD

**Issue by denzdelvillar** [OSSPhilippines/philippines-travel-level-map#45]
### 🤔 Not Existing Bug?

- [X] Yes, I'm sure that this is a bug!

### 👀 Current Behavior

Facebook users report that they are unable to share the link because Facebook flags the content as spam.

![AA5BA0F7-4342-4EA3-8EAE-9DAAEF8994B6](https://github.com/OSSPhilippines/philippines-travel-level-map/assets/87693272/769b2469-4d6a-4143-b497-b68949a258a5)

### 🎯 Expected Behavior

Posts with the link shouldn’t be flagged as spam.

### 📋 Steps To Reproduce

1. Create a post on facebook containing the link to the web app.

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/ossphilippines/philippines-travel-level-map/blob/main/code_of_conduct.md).

**Comment by warengonzaga** [comment]
Taking look into this @denzdelvillar

**Comment by warengonzaga** [comment]
Upon checking, Facebook banned/blocked the main domain name.
![image](https://github.com/OSSPhilippines/philippines-travel-level-map/assets/15052701/1845e55f-2aa8-4878-b515-126870817cc9)

What we gonna do is to use the OSSPH domain in the meantime as a backup.
https://my-philippines-travel-level.ossph.org

Nothing we can do here, it is not easy to remove the blocked/banned status from Meta (unless someone helps us to contract Meta).

**Comment by mpotane** [comment]
probably the domain is long also it's using hypens with double letters.

**Comment by warengonzaga** [comment]
> probably the domain is long also it's using hyphens with double letters.

Yes, we are going to revise this feature and implement better feature. cc: @jofftiquez
