### ISSUE TITLE
App Documentation 

### ISSUE THREAD

**Issue by digracesion** [OSSPhilippines/philippines-travel-level-map#47]
### 🤔 Not Existing Feature Request?

- [X] Yes, I'm sure, this is a new requested feature!

### 🤔 Not an Idea or Suggestion?

- [X] Yes, I'm sure, this is not idea or suggestion!

### 📋 Request Details

App documentation on how to locally install the app after forking as well as contribution guides

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/ossphilippines/philippines-travel-level-map/blob/main/code_of_conduct.md).

**Comment by warengonzaga** [comment]
hey @digracesion here's the contributing guide: https://github.com/OSSPhilippines/philippines-travel-level-map/blob/main/CONTRIBUTING.md

For the installation, it is a plain react app so you would do `yarn start` or `npm run start`
Feel free to update the README and send your PR. Thanks!

**Comment by digracesion** [comment]
made the pull request here: https://github.com/OSSPhilippines/philippines-travel-level-map/pull/48
