### ISSUE TITLE
layout bug on chrome browser

### ISSUE THREAD

**Issue by jeff-vpd** [OSSPhilippines/philippines-travel-level-map#8]
layout bug on chrome browser
![image](https://user-images.githubusercontent.com/114370793/232178094-7fcef329-36da-4d7e-9890-240221042f8e.png)

**Comment by Etewilak** [comment]
The map is too small; it's hard to color it.

**Comment by warengonzaga** [comment]
Are you able to replicate this @denzdelvillar? Unfortunately, not able to replicate the issue.

**Comment by denzdelvillar** [comment]
Can’t replicate it either. But i’ve seen several complaints like this, mostly from android users. 

If @jeff-vpd could specify the OS and Chrome browser version used here, that would help

**Comment by warengonzaga** [comment]
Agree @Etewilak @jeff-vpd, maybe share your replication steps and details more about the bug.
